# Generated by Django 5.2.6 on 2025-09-16 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_blogpost_author_blogpost_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="updated",
            new_name="updated_date",
        ),
    ]
