# Generated by Django 5.2.6 on 2025-09-28 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_topic_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="name",
            new_name="title",
        ),
    ]
