# Generated by Django 5.2.6 on 2025-09-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_name_topic_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="topic",
        ),
        migrations.AddField(
            model_name="category",
            name="topics",
            field=models.ManyToManyField(related_name="category", to="api.topic"),
        ),
    ]
