# Generated by Django 5.2.6 on 2025-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
