# Generated by Django 5.2.6 on 2025-10-29 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_blogpost_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="blog",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
    ]
