# Generated by Django 5.2.6 on 2025-10-29 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_notification_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="recipoent",
            new_name="recipient",
        ),
    ]
